export enum EventEnum {
    WALLET_CREATED = 'WALLET_CREATED',
    WALLET_DELETED = 'WALLET_DELETED',
    WALLET_UPDATED = 'WALLET_UPDATED',
    TRANSACTION_CREATED = 'TRANSACTION_CREATED',
    TRANSACTION_DELETED = 'TRANSACTION_DELETED',
}